### PR TITLE
Anb bunchlist

### PR DESCRIPTION
**Pull request by anbabaev**
The version to work with incomplete raw data

### CODE REVIEW

**Comment by gkrintir** [comment]
Hi @anbabaev  could you please resolve the conflicts ?

**Comment by anbabaev** [comment]
Resolved. Several blank lines were deleted

**Comment by capalmer85** [comment]
Hi Anton,

Will you remove the makeScanFile_2015 and add the switch that we (with
Olena) discussed?

Cheers,
Chris

**Comment by anbabaev** [comment]
OK. It is done.

**Comment by capalmer85** [comment]
@anbabaev I looked.  It is looks fantastic.  I'm happy to have it merged now.

**Pull request merged**
