### PR TITLE
Sim Fit v2

### PR DESCRIPTION
**Pull request by gkrintir**
The Sim Fit model is fits/SimCapSigma_PCCAndVtx_Fit.py (common parameters are) :

    Sigma, sigma_{1}/sigma_{2}, Frac, while the model takes also care about the
    const for PCC bkg.

Its associated Config file is the fits/SimCapSigma_PCCAndVtx_Config.json

### CODE REVIEW

**Comment by capalmer85** [comment]
@gkrintir very nice!  Can you remove the .pyc files?

**Comment by gkrintir** [comment]
@capalmer85 They ve been already removed in the commit ;D

**Review by capalmer85 — CHANGES_REQUESTED** [review]
Can /plotstmp/1 and /plotstmp/2 be renamed for PCC and VTX?  In principle, it would be nice to just be able to pass the two types of luminometers to fit together.

**Ans**: These directories are configurable and it's up to the user to change them as they wish (btw, it is also stated in the READme).

Please remove .pyc files.
**Ans**: Done

You've made changes to fits/DGConst_Fit.py, etc.  Did you make sure that the vanilla (single luminometer fits) still work?  Maybe check with the PLT rates files?
**Ans**: Already checked.

What does globalChi2 do?
**Ans**: This is the sim fit model, i.e. a global chi2 function which is minimized.

**Comment by capalmer85** [comment]
@gkrintir ah ok... I see you are removing them.  Thanks for the clean up the first time around.  I'm trying the review functionality.  Please have a look.

**Comment by gkrintir** [comment]
@capalmer85 Answers on requested changes inline.

Before merging, we can test locally. You can copy the patch below and test in your clean repo:

cp  /afs/cern.ch/user/g/gkrintir/public/ForChris/simfit.patch ~/your/repo/path
git apply --stat simfit.patch (what changes are in the patch)
git apply --check simfit.patch  (check for conflicts)
git am --signoff < simfit.patch (merge the two commits above)

**Review by capalmer85 — APPROVED** [review]

**Comment by capalmer85** [comment]
@gkrintir Thanks for the rapid response!

**Comment by capalmer85** [comment]
Resolves #21

**Pull request merged**
