### PR TITLE
remove pdf and root files from results dirs--too big

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by capalmer85** [comment]
@jsalfeld I removed some standard files (that can be easily reproduced) from the results directories.  Please look and merge if that's ok with you.

**Comment by jsalfeld** [comment]
We should store these files at our EOS dir.

**Comment by capalmer85** [comment]
For all trials, luminometers or just limited set?

**Comment by jsalfeld** [comment]
just the final LUM-15-001 ones.

**Pull request merged**
