### PR TITLE
added to read beam currents straingt from timber

### PR DESCRIPTION
**Pull request by gkrintir**
Hi @capalmer85 

in order to run timber:

1) source env.sh Timber

2) simply add the argument: https://github.com/gkrintir/VdMFramework-1/blob/7ab6edc1431bf0b5d49d9a5d2fca359bd3d1a726/4634_Configs/vdmDriverII_Config_PCC_4634.json#L66

### CODE REVIEW

**Comment by capalmer85** [comment]
@gkrintir this looks pretty awesome to me.  Could you do the following please?
1) Check that some other configuration files don't break with the update (maybe 4954).
2) Resolve the conflicts.

**Comment by gkrintir** [comment]
Hi @capalmer85  Done. 

I also put back the nominal info:

CollidingBunches = scanInfo["CollidingBunches"]
FilledBunchesB1 = scanInfo["FilledBunchesB1"]
FilledBunchesB2 = scanInfo["FilledBunchesB2"]

in the makeBeamCurrentFileII that should NOT be removed at first place. If one wants to be overwritten this should be done later (as it is done in the getCurrents() function)

**Comment by capalmer85** [comment]
@gkrintir just to confirm:  This works with the 4954 config?  If yes, please merge.

**Comment by gkrintir** [comment]
Hi @capalmer85 tested. 

I also edited now to load pytimber only under user request. README updated with instructions:

1) source env.sh Timber
2) "ReadFromTimber" : true in the makeBeamCurrentFileConfig fragment

Ready to be merged

**Pull request merged**
